# Generated by Django 2.2 on 2020-01-16 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quantity',
            name='status',
            field=models.CharField(choices=[('APP', 'Approved'), ('DSA', 'Disapproved'), ('HLD', 'OnHold')], default='HLD', max_length=3),
        ),
    ]
