# Generated by Django 2.2 on 2019-12-28 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roleofuser',
            name='name',
            field=models.CharField(default='null', max_length=50),
        ),
    ]
