# Generated by Django 2.2 on 2020-01-15 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryissued',
            name='item_status',
        ),
        migrations.AddField(
            model_name='inventorypresent',
            name='item_status',
            field=models.CharField(choices=[('APP', 'Approved'), ('DEC', 'Declined'), ('HLD', 'OnHold')], default='HLD', max_length=3),
        ),
    ]
