# Generated by Django 2.2 on 2020-01-07 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventorypresent',
            name='cropping',
        ),
    ]
