# Generated by Django 2.2 on 2020-01-16 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_quantity_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roleofuser',
            options={'verbose_name': 'User Type'},
        ),
    ]
