# Generated by Django 2.2 on 2020-01-16 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200116_1151'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='items',
            options={'verbose_name': 'List of Item'},
        ),
    ]
