# Generated by Django 2.2 on 2020-01-07 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200107_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorypresent',
            name='picture',
            field=models.ImageField(blank=True, default='https://00e9e64bacdf5028dff6ebe83b795ecea31d8c3c05e73ca87b-apidata.googleusercontent.com/download/storage/v1/b/dudic_inventory/o/inventory_thumbnails%2Fsample_image.png?qk=AD5uMEu9YzIpCNwCiiRKn4z7qeqL3eBWUudUUHkf5gAKbg77mRAjbziKgu1McMP5n5LaYsBLzUiSR1T8SfMGyVNCV0CI4T5Wu2G2GnCBytztUFiE2BbvlSp6yiogJ11zPnkFVF9HGtNBbvZr2qYTZJS3Zb8FAlKhwB6Na_uW7-rcCLhccTyxhPrXttW08p1SrdUh0YBWzNiJF7Goq37zisxzNtHfeYs2Yu_YcPloP5gs7HneWE2l0OLoLnVsJAUgUzezdGi2fGDsdHEYSKZKzCr7nTcUeyQL9SBOXOS36PcnUPt81X_uVGh9Ju-LnYZxJIwPbBIRvp3_mmJH4j8TUURPU9lZ1ZIjpZV1dpYJvwUAqjMdAl2IUrYqPgG83M-yJTKNcPE1_mDrBsUO0RvwKL16Fx7kPGR-TFPLE5u4gQnS0Uh5qsiIENwgFKO11mbzkjtjgA5ADCoojG5diZmpF5xe_coLzwNYOrmfECr6CKQv_Xl_pQehVcpPc4th_JqQRUM85gVAR64afZBbYuQX004pBc4hMRDka_xGgNNQDVi36ni1UM9O35xIX-795EGFdmEJFBXo7lfx2puCLJZtxPKfKYRfJ5_Ph4qCktWQlIoFEIbgAmbGzIprTOEqAFw2MqP-7-YWkadiPS-17QPg62YWdP2XhcovndaVZUuuS4060VGjEe0yX0KBawlQMYCjlWQj1nc_WxhClpKSfWgxLfdwdzZb3R1LLPwtPw_ciIKs8PtOws0-4Lv5oTBfrSTQQsU5dm1bVLKqWHAe31xkusZ1NWLJwTiiJocvsu23jXQpmEUoyngHkZGWLwn7S-4vT2LKuieJyUOv', null=True, upload_to='inventory_thumbnails/'),
        ),
    ]
