# Generated by Django 2.2 on 2020-01-15 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_inventorypresent_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryissued',
            name='item_name',
            field=models.ManyToManyField(to='users.ItemNames'),
        ),
    ]
