# Generated by Django 2.2 on 2019-12-30 08:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20191229_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryissued',
            name='get_users',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
