# Generated by Django 2.2.9 on 2020-08-24 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_inventoryissued_item_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemnames',
            name='quantity',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inventorypresent',
            name='picture',
            field=models.ImageField(blank=True, default='/home/dic/dudic-inventory/inventory/static/admin/img/sample_image.svg', null=True, upload_to='inventory_thumbnails/'),
        ),
    ]
