# Generated by Django 2.2 on 2019-12-30 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20191230_1002'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventoryissued',
            old_name='get_users',
            new_name='username',
        ),
    ]
