# Generated by Django 2.2 on 2020-01-07 12:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20200107_1138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryissued',
            name='get_users',
        ),
        migrations.AddField(
            model_name='inventoryissued',
            name='get_users',
            field=models.ManyToManyField(related_name='issued', to=settings.AUTH_USER_MODEL),
        ),
    ]
