# Generated by Django 2.2 on 2020-01-07 12:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20200107_1219'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventoryissued',
            old_name='get_user_type',
            new_name='user_type',
        ),
        migrations.RemoveField(
            model_name='inventoryissued',
            name='get_users',
        ),
        migrations.RemoveField(
            model_name='inventoryissued',
            name='user',
        ),
        migrations.AddField(
            model_name='inventoryissued',
            name='user',
            field=models.ManyToManyField(related_name='issued', to=settings.AUTH_USER_MODEL),
        ),
    ]
