# Generated by Django 2.2 on 2019-12-30 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20191230_1602'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventoryissued',
            old_name='get_user',
            new_name='get_users',
        ),
    ]
