# Generated by Django 2.2 on 2020-01-07 12:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20200107_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryissued',
            name='get_users',
            field=models.ManyToManyField(related_name='issued', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='inventoryissued',
            name='user',
        ),
        migrations.AddField(
            model_name='inventoryissued',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
