# Generated by Django 2.2 on 2020-01-07 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_inventoryissued_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorypresent',
            name='picture',
            field=models.ImageField(blank=True, default='/static/admin/img/sample_image.svg', null=True, upload_to='inventory_thumbnails/'),
        ),
    ]
