# Generated by Django 2.2 on 2020-01-07 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20200107_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorypresent',
            name='picture',
            field=models.ImageField(blank=True, default='/Users/prady/github/new/dudic-inventory/inventory/static/admin/img/sample_image.svg', null=True, upload_to='inventory_thumbnails/'),
        ),
    ]
