# Generated by Django 2.2 on 2019-12-30 08:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20191230_0844'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryissued',
            name='assigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued', to=settings.AUTH_USER_MODEL),
        ),
    ]
