# Generated by Django 2.2 on 2019-12-30 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_inventoryissued_assigned_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventoryissued',
            old_name='assigned_by',
            new_name='user',
        ),
    ]
