# Generated by Django 2.2 on 2019-12-30 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20191230_0958'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventoryissued',
            old_name='user',
            new_name='assigned_by',
        ),
    ]
