# Generated by Django 2.2 on 2019-12-30 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20191230_1001'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventoryissued',
            old_name='assigned_by',
            new_name='user',
        ),
    ]
