# Generated by Django 2.2 on 2019-12-30 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20191230_1558'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventoryissued',
            old_name='username',
            new_name='get_user',
        ),
    ]
