# Generated by Django 2.2 on 2019-12-30 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20191230_1604'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryissued',
            name='item_name',
        ),
        migrations.AddField(
            model_name='inventoryissued',
            name='item_name',
            field=models.ManyToManyField(to='users.InventoryPresent'),
        ),
    ]
